// <auto-generated />
namespace Pablo.Gallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class oddkeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oddkeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201612010222277_odd-keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
